services:
  outline:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BASE_IMAGE: goka-outline-base
    image: outline-local:prod
    env_file:
      - ./docker.env
    depends_on:
      - postgres
      - redis
    ports:
      - "80:80"
    volumes:
      - storage-data:/var/lib/outline/data
    restart: unless-stopped

  redis:
    image: redis:8-alpine
    command:
      - redis-server
      - --maxmemory 512mb
      - --maxmemory-policy allkeys-lru
      - --save ""
      - --appendonly no
      - /redis.conf
    volumes:
      - ./redis.conf:/redis.conf
      - redis-data:/data
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    restart: unless-stopped

  postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: outline
    command:
      - postgres
      - -c shared_buffers=512MB
      - -c effective_cache_size=1536MB
      - -c work_mem=16MB
      - -c maintenance_work_mem=128MB
      - -c max_connections=80
    deploy:
      resources:
        limits:
          memory: 1536M
        reservations:
          memory: 512M
    restart: unless-stopped

volumes:
  storage-data:
  redis-data:
